# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e750de274c64c00a2c20a49e43244c10f8d4cac176e11cadc912af55e4ef4f1fc385f0d14e63155d3a80911c32e6eeab37a40d247a73a44e857073105b8123

test:
  secret_key_base: 654891815bc0afbd5ae61af0ca9865257042df62c9f68763c6cb22b82cab8491f6fdcc761477e8b529f8c8bb5171b9b0d15466f9d110b26604e6c23d8d1202dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
